--Find all missing customer IDs

CREATE TABLE Customers (
 customer_id INT
);

INSERT INTO Customers (customer_id)
VALUES (1), (2), (3), (5), (7), (8), (10);

SELECT * FROM CUSTOMERS

WITH RECURSIVE NUMBERS AS (
SELECT 1 AS ID
UNION ALL
SELECT ID+1
FROM NUMBERS 
WHERE ID<(SELECT MAX(CUSTOMER_ID) FROM CUSTOMERS)
)

SELECT ID AS MISSING_ID
FROM NUMBERS N
LEFT JOIN CUSTOMERS C ON N.ID=C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL
ORDER BY MISSING_ID 
